services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: src/DevHabit.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
    # Seq
    # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.seq:4317
    # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    # Aspire Dashboard
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
    - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  devhabit.seq:
    image: datalust/seq:latest
    ports:
      - 8080:80
      - 5431:5431
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.container/seq_data:/data

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:13
    ports:
      - 18888:18888
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true